version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=djangoresthome
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=djangoresthome
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    